### PR TITLE
Cleanup of the FAQ pages

### PR DESCRIPTION
**Pull request by Zi-SH**
I've been working on cleaning up the FAQ page as there are some dated issues and some FAQ items missing/not listed/out of order.

I've opted to split the Windows and Linux FAQ as each has similar topics that require different answers.

My only remaining concern over this is the index.md, and that concern is solely buttons not being perfectly aligned. Could probably clean that up with some inline html.

### CODE REVIEW

**Comment by philpax** [comment]
Sorry about letting this drift for so long. Are you still interested in bringing it up to date?

**Comment by Zi-SH** [comment]
I have no problem bringing it up to date, but will it sit this long again if I do?

**Comment by Zi-SH** [comment]
Should be good to go. Gave it an additional combing to fix some page formatting consistency, but nothing major.

**Comment by philpax** [comment]
Yeah sorry, larger reorganisations of the FAQ aren't really my department. I think this is up to @reiichi001 to weigh in on.

**Comment by reiichi001** [comment]
Hi there! I don't quite have the time/energy look over everything right now, as the changes here would also involve significant adjustments to Franzbot's codebase as the bot faq command heavily references posts on this repo.

I'm not personally a fan of splitting the launcher faq into Windows and Linux because that means a bunch of the posts are duplicated, which increases the maintenance cost to keep them in sync, and could be solved by improving the existing launcher FAQ into more sections if we want dedicated Windows-Specific and Linux-Specific things. (As likely apparent, the FAQ entries themselves are in need of some rework as a bunch of older Linux bandaids no longer apply because xlcore changes a lot of things. 

When I have more time (and the appropriate motivation to write), I'd like to reference this PR for the reorganization mentioned above, as it does have new content that should be in the FAQ in general, like xlcore password saving.

**Pull request closed without merging**
