### PR TITLE
where plogon

### PR DESCRIPTION
**Pull request by kalilistic**

### CODE REVIEW

**Comment by NotNite** [comment]
Is this linted? It doesn't look like it.

**Comment by kalilistic** [comment]
I should add, this list was confirmed a little while back when we were looking at making this a displayed message in the plugin installer. The PR died but I thought we could salvage the info for the FAQ/Franzbot at least to help support.

**Comment by kalilistic** [comment]
Any changes needed?

**Comment by reiichi001** [comment]
Looks good to me. I'm gonna merge it

**Pull request merged**
